contents:
  repositories:
    - https://packages.wolfi.dev/os
    - https://alauda-mesh.github.io/istio-base-images
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - https://alauda-mesh.github.io/istio-base-images/melange.rsa.pub
  packages:
    - wolfi-baselayout
    - alauda-baselayout
    - ca-certificates-bundle
    - tzdata

accounts:
  groups:
    - groupname: nonroot
      gid: 65535
    - groupname: istio-proxy
      gid: 1337
  users:
    - username: nonroot
      uid: 65535
      gid: 65535
      shell: /sbin/nologin
    - username: istio-proxy
      uid: 1337
      gid: 1337
      homedir: /nonexistent
      shell: /sbin/nologin
  run-as: 65535

archs:
  - x86_64
  - aarch64

