name: Publish
on:
  workflow_call:
    inputs:
      owner:
        required: true
        type: string
      image:
        required: true
        type: string
      version:
        required: false
        type: string
      melange_package:
        default: false
        type: boolean
    secrets:
      gcr_token:
        description: 'Personal Access Token to be used to push to GitHub Container Registry'
        required: true
jobs:
  publish:
    name: Publish to GCR (${{ inputs.image }})
    timeout-minutes: 150 # required due to hadolint (need to improve the build time somehow)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup QEMU
        if: ${{ inputs.melange_package }}
        uses: docker/setup-qemu-action@v3
      - name: Build apk package (melange)
        uses: chainguard-dev/actions/melange-build@main
        if: ${{ inputs.melange_package }}
        with:
          sign-with-temporary-key: true
          config: ${{ inputs.image }}/${{ inputs.image }}.melange.yaml
          repository-path: ${{ github.workspace }}/${{ inputs.image }}/packages
          archs: x86_64,aarch64
      - name: Publish to GitHub Container Registry
        uses: chainguard-images/actions/apko-publish@main
        with:
          config: configs/${{ inputs.image }}.apko.yaml
          tag: ghcr.io/${{ inputs.owner }}/${{ inputs.image }}:${{ inputs.version }}
          generic-user: ${{ inputs.owner }}
          generic-pass: ${{ secrets.gcr_token }}
          annotations: org.opencontainers.image.source:https://github.com/${{ inputs.owner }}/${{ github.repository }},org.opencontainers.image.version:${{ inputs.version }}
          build-repository-append: ${{ github.workspace }}/${{ inputs.image }}/packages
          keyring-append: ${{ inputs.melange_package && format('{0}/melange.rsa.pub', github.workspace) || '' }}
