name: Istio Distroless
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_shared**'
      - '.github/workflows/istio-distroless.yml'
      - 'configs/distroless.apko.yaml'
  pull_request:
    paths:
      - '.github/workflows/_shared**'
      - '.github/workflows/istio-distroless.yml'
      - 'configs/distroless.apko.yaml'
  workflow_dispatch:
jobs:
  build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_shared_build.yaml
    with:
      owner: ${{ github.repository_owner }}
      image: distroless
      version: pr-${{ github.event.pull_request.head.sha }}
  publish:
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/_shared_publish.yaml
    with:
      owner: ${{ github.repository_owner }}
      image: distroless
      revision: ${{ github.sha }}
    secrets:
      gcr_token: ${{ secrets.GITHUB_TOKEN }}
