name: Build istio base images

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_shared**'
      - '.github/workflows/istio-base-images.yaml'
      - 'configs/**.yaml'
      - 'docker/*'
  pull_request:
    paths:
      - '.github/workflows/_shared**'
      - '.github/workflows/istio-base-images.yaml'
      - 'configs/**.yaml'
      - 'docker/*'
  workflow_dispatch:

jobs:
  generate-version:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Generate version
        id: set-version
        run: |
          echo "version=$(date -u +'%Y-%m-%dT%H-%M-%S')" >> ${GITHUB_OUTPUT}
        shell: sh

  build:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        image: [distroless, iptables]
    uses: ./.github/workflows/_shared_build.yaml
    with:
      owner: ${{ github.repository_owner }}
      image: ${{ matrix.image }}
      version: pr-${{ github.event.pull_request.head.sha }}

  publish:
    if: github.event_name != 'pull_request'
    needs: [generate-version]
    strategy:
      matrix:
        image: [distroless, iptables]
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/_shared_publish.yaml
    with:
      owner: ${{ github.repository_owner }}
      image: ${{ matrix.image }}
      version: ${{ needs.generate-version.outputs.version }}
    secrets:
      gcr_token: ${{ secrets.GITHUB_TOKEN }}

  publish-debug-base:
    if: github.event_name != 'pull_request'
    needs: [generate-version]
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Istio debug image
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: docker/Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/base:${{ needs.generate-version.outputs.version }}
