name: Build and Upload Wolfi Packages
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  upload-wolfi-packages:
    name: Build and upload Wolfi packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Generate package list
        run: |
          cd wolfi
          # Copy package resources to workdir
          RESOURCES=$(ls -d */)
          for resource in $RESOURCES; do
            cp -r $resource/* .
          done
          # Create package list
          APK_LIST=$(find *.yaml -type 'f' | tr '\n' ',')
          echo "APK_LIST=$APK_LIST" >> $GITHUB_ENV

      # Write the signing key from GitHub Secret
      - name: Write Signing Key
        run: |
          echo "${{ secrets.MELANGE_SIGNING_KEY }}" > melange.rsa
          chmod 600 melange.rsa

      # Build APKs with melange
      - name: Build APKs
        id: melange
        uses: chainguard-dev/actions/melange-build@main
        with:
          archs: aarch64,x86_64
          empty-workspace: false
          multi-config: ${{ env.APK_LIST }}
          workdir: ./wolfi

      # Copy the public key to the packages directory
      - name: Copy Public Key to Packages
        run: |
          if [ -f "melange.rsa.pub" ]; then
            cp melange.rsa.pub ./packages/
            echo "Copied melange.rsa.pub to ./packages/"
          else
            echo "melange.rsa.pub not found in the workspace directory"
            exit 1
          fi

      # Deploy packages to gh-pages branch
      # This action will create the gh-pages branch for you if it doesn't exist.
      # It will also overwrite the contents of the branch on each run
      # to ensure it always reflects the latest package builds.
      - name: Deploy packages to gh-pages branch
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Wolfi APKs to gh-pages'
